config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  root 'main#index'
  resources :newsletters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
	validates :name, presence: true
	validates :url, presence: true
	validates :category, presence: true
          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@newsletters = Newsletter.all
  end

  
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
	def index
		@newsletters = Newsletter.all

	end

	def show
	    @newsletter = Newsletter.find(params[:id])
	end


	def new
		@newsletter = Newsletter.new
	end

	def edit
		@newsletter = Newsletter.find(params[:id])
	end


	def create
		@newsletter = Newsletter.new(newsletter_params)
		 
		if @newsletter.save
			redirect_to @newsletter
		else
			render 'new'
		end
	  	
	end

	def update
	  @newsletter = Newsletter.find(params[:id])
	 
	  if @newsletter.update(newsletter_params)
	    redirect_to @newsletter
	  else
	    render 'edit'
	  end
	end


	def destroy
	  @newsletter = Newsletter.find(params[:id])
	  @newsletter.destroy
	 
	  redirect_to newsletters_path
	end

	private
	  def newsletter_params
	    params.require(:newsletter).permit(:name, :url, :category)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>NewsletterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class ="container">
    <%= yield %>
	</div>
  </body>
</html>

app/views/main/index.html.erb
<h1>HEY MATT I MADE THAT WEBSITE WE WERE TALKING ABOUT</h1>

<td><%= link_to 'Building a list of newsletters', newsletters_path %></td>
 

app/views/newsletters/_form.html.erb
<%= form_with model: @newsletter, local: true do |form| %>  

<% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@newsletter.errors.count, "error") %> prohibited
        this newsletter from being saved:
      </h2>
      <ul>
        <% @newsletter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>
  <p>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<h1>Listing newsletters</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Homepage</th>
  </tr>
 
  <% @newsletters.each do |newsletter| %>
    <tr>
      <td><%= newsletter.name %></td>
      <td><%= newsletter.category %></td>
      <td><%= link_to 'Home', newsletter.url %></td>
      <td><%= link_to 'Show', newsletter_path(newsletter) %></td>
      <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
       <td><%= link_to 'Destroy', newsletter_path(newsletter),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
  <%= link_to 'Add a Newsletter', '/newsletters/new' %>
</table>

app/views/newsletters/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<h1>Listing newsletters</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Homepage</th>
  </tr>
  
    <tr>
      <td><%= @newsletter.name %></td>
      <td><%= @newsletter.category %></td>
      <td><%= link_to 'Home', @newsletter.url %></td>
    </tr>
</table>

<%= link_to 'Back', newsletters_path %>